// server/api/hives/index.post.js
import { createClient } from '@supabase/supabase-js'

export default defineEventHandler(async (event) => {
  const config = useRuntimeConfig()

  const supabase = createClient(
    config.public.supabaseUrl, 
    config.public.supabaseAnonKey
  )
  
  try {
    const body = await readBody(event)
    
    // Validate required fields
    if (!body.name || !body.name.trim()) {
      return { error: 'Hive name is required' }
    }

    // Create new hive object - let Supabase generate the UUID
    const newHive = {
      // uuid will be auto-generated by Supabase
      name: body.name.trim(),
      description: body.description?.trim() || body.name.trim(),
      latitude: body.latitude || null,
      longitude: body.longitude || null,
      installation_date: body.installation_date || new Date().toISOString().split('T')[0],
      is_active: body.is_active !== undefined ? body.is_active : true
      // created_at and updated_at can also be auto-generated if you set defaults
    }

    // Insert into database
    const { data, error } = await supabase
      .from('hives')
      .insert([newHive])
      .select()
      .single()

    if (error) throw error
    
    return { data }
  } catch (error) {
    return { error: error.message }
  }
})