-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.alerts (
  id integer NOT NULL DEFAULT nextval('alerts_id_seq'::regclass),
  hive_id integer NOT NULL,
  alert_type character varying NOT NULL,
  severity character varying NOT NULL,
  title character varying NOT NULL,
  message text NOT NULL,
  threshold_value numeric,
  actual_value numeric,
  sensor_id integer,
  resolved boolean DEFAULT false,
  resolved_by character varying,
  resolved_notes text,
  created_at timestamp with time zone DEFAULT now(),
  resolved_at timestamp with time zone,
  CONSTRAINT alerts_pkey PRIMARY KEY (id),
  CONSTRAINT alerts_sensor_id_fkey FOREIGN KEY (sensor_id) REFERENCES public.sensors(id),
  CONSTRAINT alerts_hive_id_fkey FOREIGN KEY (hive_id) REFERENCES public.hives(id)
);
CREATE TABLE public.daily_summaries (
  id integer NOT NULL DEFAULT nextval('daily_summaries_id_seq'::regclass),
  hive_id integer NOT NULL,
  date date NOT NULL,
  avg_temperature numeric,
  min_temperature numeric,
  max_temperature numeric,
  temperature_readings_count integer DEFAULT 0,
  avg_humidity numeric,
  min_humidity numeric,
  max_humidity numeric,
  humidity_readings_count integer DEFAULT 0,
  avg_weight numeric,
  min_weight numeric,
  max_weight numeric,
  weight_change_from_previous_day numeric,
  weight_readings_count integer DEFAULT 0,
  total_readings integer DEFAULT 0,
  alerts_count integer DEFAULT 0,
  critical_alerts_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT daily_summaries_pkey PRIMARY KEY (id),
  CONSTRAINT daily_summaries_hive_id_fkey FOREIGN KEY (hive_id) REFERENCES public.hives(id)
);
CREATE TABLE public.hives (
  id integer NOT NULL DEFAULT nextval('hives_id_seq'::regclass),
  uuid uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  name character varying NOT NULL,
  description text,
  latitude numeric,
  longitude numeric,
  installation_date date DEFAULT CURRENT_DATE,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  created_by uuid,
  CONSTRAINT hives_pkey PRIMARY KEY (id),
  CONSTRAINT hives_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT hives_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.payments (
  id integer NOT NULL DEFAULT nextval('payments_id_seq'::regclass),
  user_id uuid NOT NULL,
  subscription_id integer,
  stripe_payment_intent_id character varying UNIQUE,
  stripe_charge_id character varying,
  amount numeric NOT NULL,
  currency character varying DEFAULT 'USD'::character varying,
  status character varying NOT NULL,
  payment_method character varying,
  failure_reason text,
  refunded_amount numeric DEFAULT 0,
  description text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT payments_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.user_subscriptions(id)
);
CREATE TABLE public.queen_status (
  id integer NOT NULL DEFAULT nextval('queen_status_id_seq'::regclass),
  hive_id integer NOT NULL,
  queen_age_days integer,
  last_seen_date date,
  laying_pattern character varying DEFAULT 'unknown'::character varying,
  queen_marked boolean DEFAULT false,
  queen_color character varying,
  queen_origin character varying,
  replaced_date date,
  replacement_reason character varying,
  notes text,
  status character varying DEFAULT 'active'::character varying,
  confidence_level character varying DEFAULT 'medium'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT queen_status_pkey PRIMARY KEY (id),
  CONSTRAINT queen_status_hive_id_fkey FOREIGN KEY (hive_id) REFERENCES public.hives(id)
);
CREATE TABLE public.sensor_readings (
  id integer NOT NULL DEFAULT nextval('sensor_readings_id_seq'::regclass),
  sensor_id integer NOT NULL,
  hive_id integer NOT NULL,
  sensor_type character varying NOT NULL,
  value numeric NOT NULL,
  unit character varying NOT NULL,
  reading_time timestamp with time zone DEFAULT now(),
  signal_strength integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sensor_readings_pkey PRIMARY KEY (id),
  CONSTRAINT sensor_readings_hive_id_fkey FOREIGN KEY (hive_id) REFERENCES public.hives(id),
  CONSTRAINT sensor_readings_sensor_id_fkey FOREIGN KEY (sensor_id) REFERENCES public.sensors(id)
);
CREATE TABLE public.sensors (
  id integer NOT NULL DEFAULT nextval('sensors_id_seq'::regclass),
  uuid uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  hive_id integer NOT NULL,
  sensor_type character varying NOT NULL,
  name character varying,
  model character varying,
  battery_level integer DEFAULT 100,
  is_online boolean DEFAULT true,
  last_reading_at timestamp with time zone,
  calibration_offset numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sensors_pkey PRIMARY KEY (id),
  CONSTRAINT sensors_hive_id_fkey FOREIGN KEY (hive_id) REFERENCES public.hives(id)
);
CREATE TABLE public.subscription_plans (
  id integer NOT NULL DEFAULT nextval('subscription_plans_id_seq'::regclass),
  name character varying NOT NULL UNIQUE,
  display_name character varying NOT NULL,
  description text,
  price_monthly numeric NOT NULL,
  price_yearly numeric,
  stripe_price_id_monthly character varying UNIQUE,
  stripe_price_id_yearly character varying UNIQUE,
  stripe_product_id character varying UNIQUE,
  features jsonb NOT NULL DEFAULT '{}'::jsonb,
  limits jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL,
  username character varying UNIQUE,
  first_name character varying,
  last_name character varying,
  phone character varying,
  company_name character varying,
  avatar_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_subscriptions (
  id integer NOT NULL DEFAULT nextval('user_subscriptions_id_seq'::regclass),
  user_id uuid NOT NULL,
  plan_id integer NOT NULL,
  stripe_subscription_id character varying UNIQUE,
  stripe_customer_id character varying,
  status character varying NOT NULL DEFAULT 'inactive'::character varying,
  billing_cycle character varying NOT NULL DEFAULT 'monthly'::character varying,
  current_period_start timestamp with time zone,
  current_period_end timestamp with time zone,
  trial_start timestamp with time zone,
  trial_end timestamp with time zone,
  canceled_at timestamp with time zone,
  cancellation_reason text,
  next_billing_date timestamp with time zone,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT user_subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.subscription_plans(id),
  CONSTRAINT user_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);